<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-08-14 22:35
=======
# Generated by Django 3.2.20 on 2023-08-15 00:56
>>>>>>> dbc4544c63e8b806a8c82f1908f81605cc58147c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
            ],
        ),
    ]
