# Generated by Django 4.2.4 on 2023-08-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='feedback',
        ),
    ]
