# Generated by Django 4.2.4 on 2023-08-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadPage', '0006_alter_post_target_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='upload_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='target',
            field=models.CharField(max_length=200),
        ),
    ]
