# Generated by Django 4.2.4 on 2023-08-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadPage', '0007_rename_url_post_upload_url_alter_post_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
